[project]
name = "clarity-sbtc-payments"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.sbtc-payment]
path = "contracts/sbtc-payment.clar"

[contracts.sbtc-token]
path = "contracts/sbtc-token.clar"
depends_on = ["sbtc-payment"]

# [contracts.bogus-token]
# path = "contracts/bogus-token.clar"

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
